In [51]:
import OpenGeoSys
import numpy as np
import rasterio

file_name = 'Recharge2013_2019_FIXED.tif'
with rasterio.open(file_name) as src:
    band1 = src.read(1)
    height = band1.shape[0]
    width = band1.shape[1]
    cols, rows = np.meshgrid(np.arange(width), np.arange(height))
    xs, ys = rasterio.transform.xy(src.transform, rows, cols)
    lons= np.array(xs)[0]
    lats = np.array(ys).T[0]
band2 = 1000000*band1/1242399685

def find_nearest(array, value):
    if type(value) == float:
        idx = (np.abs(array - value)).argmin()
    else:
        idx = np.zeros(len(value))
        array = np.asarray(array)
        for i in range(len(value)):
            idx[i] = (np.abs(array - value[i])).argmin()
    return idx

# source term for the benchmark
class Rain(OpenGeoSys.SourceTerm):
    def getFlux(self, t, coords, primary_vars):
        x, y, z = coords
        idxX = find_nearest(lons , x)
        idxY = find_nearest(lats , y)
        value = band2[idxY,idxX] 
        Jac = [ 0.0 ]
        return (value, Jac)

# instantiate source term object referenced in OpenGeoSys' prj file
rainSourceTerm = Rain()

ModuleNotFoundError: No module named 'OpenGeoSys'

In [60]:
# file_name = 'MEAN_RECHARGE_1998_2019.asc'
# with rasterio.open(file_name) as src:
#     band1 = src.read(1)
#     height = band1.shape[0]
#     width = band1.shape[1]
#     cols, rows = np.meshgrid(np.arange(width), np.arange(height))
#     xs, ys = rasterio.transform.xy(src.transform, rows, cols)
#     lons= np.array(xs)[0]
#     lats = np.array(ys).T[0]
# band2 = band1/1242399685

# def find_nearest(array, value):
#     if type(value) == float:
#         idx = (np.abs(array - value)).argmin()
#     else:
#         idx = np.zeros(len(value))
#         array = np.asarray(array)
#         for i in range(len(value)):
#             idx[i] = (np.abs(array - value[i])).argmin()
#     return idx

In [61]:
# find_nearest(lons , 1.1)

0

array([1.000e+00, 2.239e+03])

array([12.1, 20.6], dtype=float32)

array([[9.73921720e-09, 1.65808158e-08, 1.65808158e-08, ...,
        1.84320713e-08, 1.67417937e-08, 1.66613055e-08],
       [0.00000000e+00, 2.73663946e-08, 1.65808158e-08, ...,
        1.67417937e-08, 1.83515816e-08, 1.82710935e-08],
       [0.00000000e+00, 1.66613055e-08, 1.65808158e-08, ...,
        1.83515816e-08, 1.83515816e-08, 1.82710935e-08],
       ...,
       [8.85383354e-09, 8.69285490e-09, 8.69285490e-09, ...,
        2.31004557e-09, 2.39858401e-09, 2.35029042e-09],
       [8.61236520e-09, 8.77334384e-09, 5.28815344e-09, ...,
        2.31004557e-09, 2.36638828e-09, 2.30199664e-09],
       [7.75112891e-09, 8.29040792e-09, 4.87765734e-09, ...,
        2.31004557e-09, 2.35029042e-09, 2.26175198e-09]])

1242399685.039386